[ADD] test를 위한 초기세팅
wecode-bootcamp-korea/36-2nd-DGV-backend pull request #6
Opened 2022-09-05 08:00 UTC by seatbelt92

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- software test를 위한 초기세팅

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. app.js/ server.js 분리
2. supertest 설치 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
-  test를 통한 코드의 신뢰성을 확보하기 위해 파일 분리를 진행했습니다. 

<br />

## :: 기타 질문 및 특이 사항

2022-09-05 08:22 UTC, bigfanoftim requested changes
뭔가 좀 부족한 것 같은데 다시 한번 자료를 확인해 보시겠어요?

2022-09-05 08:23 UTC, bigfanoftim commented
> 뭔가 좀 부족한 것 같은데 다시 한번 자료를 확인해 보시겠어요?

PR을 올려 리뷰 요청을 하실 때에는 가장 먼저 `Files changed`를 확인하는 것이 기본 매너입니다!

2022-09-06 02:16 UTC, bigfanoftim requested changes

2022-09-06 02:16 UTC, bigfanoftim commented on .env.test
> +TYPEORM_LOGGING =TRUE
.gitignore에 추가해 주세요.

2022-09-06 02:28 UTC, seatbelt92 commented on .env.test
> +TYPEORM_LOGGING =TRUE
멘토님, 해당 브랜치의 gitginore에 ".env.test"를 추가하고 PR을 작성한 것인데.. 혹시 처음 진행했던 커밋에 해당 파일이 포함되어 있기 때문에 반영이 안 된 것일까요??

그렇다면 gitignore에 반영이 되기 위해서는 어떻게 진행해야 할까요?
깃 리베이스를 통해서 관련 커밋들을 취합하는 방식으로 해면 되는 걸까요?

2022-09-06 02:30 UTC, seatbelt92 commented on .env.test
> +TYPEORM_LOGGING =TRUE
그리고 위 코멘트에서 말씀하셨던 파일 체인지부터 확인하라는 말씀은 구체적으로 어떤 것인지 설명 부탁드려도 괜찮을까요?

2022-09-06 02:49 UTC, bigfanoftim commented on .env.test
> +TYPEORM_LOGGING =TRUE
<img width="284" alt="image" src="https://user-images.githubusercontent.com/62135254/188536576-c1e0da6f-289a-45d1-be33-0d21ad914c4b.png">
PR을 올리면 해당 PR에 해당하는 수정사항들이 보이게 됩니다. 항상 여기에 올라오면 안될 것들이 올라오지는 않았는지 확인해야 합니다.

이미 트래킹된 파일에 대해서는 캐시를 지워줘야 합니다. 관련 git 명령어를 구글링해보세요!

2022-09-07 02:07 UTC, bigfanoftim commented
아직 해결이 안됐습니다.
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/62135254/188772708-8fe9a885-eb33-41aa-970a-ead0ee0b475b.png">

2022-09-07 02:51 UTC, seatbelt92 commented
> 아직 해결이 안됐습니다. <img alt="image" width="1393" src="https://user-images.githubusercontent.com/62135254/188772708-8fe9a885-eb33-41aa-970a-ead0ee0b475b.png">

깃리베이스 적용 및 파일체인지 확인하여 다시 요청드립니다..

2022-09-07 07:13 UTC, bigfanoftim approved these changes
LGTM 👍

2022-09-07 07:13 UTC, merged